const themeList = [
    "github",
    "eclipse",
    "nord_dark",
    "mono_industrial",
    "cloud9_night_low_color",
    "kr_theme",
    "twilight",
    "solarized_dark",
    "dawn",
    "iplastic",
    "monokai",
    "idle_fingers",
    "cloud9_night",
    "one_dark",
    "cloud_editor_dark",
    "textmate",
    "solarized_light",
    "merbivore_soft",
    "vibrant_ink",
    "clouds",
    "cobalt",
    "gruvbox_dark_hard",
    "sqlserver",
    "pastel_on_dark",
    "crimson_editor",
    "katzenmilch",
    "chrome",
    "cloud_editor",
    "dreamweaver",
    "tomorrow_night",
    "ambiance",
    "kuroir",
    "chaos",
    "tomorrow_night_eighties",
    "merbivore",
    "clouds_midnight",
    "tomorrow_night_bright",
    "gob",
    "tomorrow_night_blue",
    "xcode",
    "tomorrow",
    "cloud9_day",
    "github_dark",
    "terminal",
    "gruvbox",
    "dracula",
    "gruvbox_light_hard",
];

for (let i = 0; i <= themeList.length - 1; i++) {
    let opt = document.createElement("option");
    opt.setAttribute("value", themeList[i]);
    opt.innerText = themeList[i];
    themeSelector.appendChild(opt);
}
